export const diaryPreludeButtonCopyMap = {
  weatherOnly: {
    sunny: "阳光正好，落笔生温。",
    cloudy: "闲坐，写给微暗的云层",
    rainy: "让雨声打湿纸页的边缘。",
    windy: "驻足，感受风穿过纸页",
  },
  moodOnly: {
    calm: "岁月无声，落笔无痕。",
    joyful: "封存，心头闪烁的微光",
    anxious: "不要怕，让文字替你呼吸。",
    melancholy: "在沉默中，给自己留一盏灯。",
    relieved: "释怀，与此刻的自己言和",
  },
  combo: {
    "sunny|calm": "展卷，沐浴此刻的暖阳",
    "sunny|joyful": "带着日光落笔",
    "sunny|anxious": "在喧嚣里找回安静",
    "sunny|melancholy": "把这份反差放进文字里",
    "sunny|relieved": "致未来，阴霾散尽后的释怀",
    "rainy|calm": "借这一场雨洗净浮躁",
    "rainy|joyful": "记录雨天的温情",
    "rainy|anxious": "让文字分担一点潮湿",
    "rainy|melancholy": "有些话，只对纸讲",
    "rainy|relieved": "今天，雨过天晴",
    "cloudy|calm": "就这样，静默记录",
    "cloudy|joyful": "记录这转瞬即逝的光",
    "cloudy|anxious": "把沉甸甸的念头写下来",
    "cloudy|melancholy": "沉淀，与这灰色的一天和解",
    "cloudy|relieved": "展卷，任旧事如浮云般散去",
    "windy|calm": "就这样安静写下",
    "windy|joyful": "带着风落笔",
    "windy|anxious": "理清杂乱，安顿下来",
    "windy|melancholy": "记录时间的凋零",
    "windy|relieved": "告别过去，拥抱今日",
  },
} as const;
